### ISSUE TITLE
Nothing returned from smb2_connect_share of libsmb2.h

### ISSUE THREAD

**Issue by zhao15** [amosavian/AMSMB2#1]
Hi, I am trying to connect to my Apple TC as below:
dispatch_queue.async {
            let client = AMSMB2(url: URL(string: "smb://192.168.2.1"), credential: URLCredential(user: "user", password: "Password", persistence: .permanent))!
            client.connectShare(name: "folder") { error in
                handler(client, error)
            }
        }
but the handler can't be called, and I found it that smb2_connect_share has never responded.
Could you please give me any direction about it? 
thank your very much.

**Comment by amosavian** [comment]
I forgot to mention that url must have share part. I will fix library that it won't be needed anymore.
