### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by lei85325** [amosavian/AMSMB2#101]
Hello, I use Objective-c to integrate AMSMB2 through pod. I passed the login and get the primary list function, but encountered problems below:
1. For the primary list, I have no way to determine whether it is a folder type.
2. I cannot enter the lower level list based on the path of the primary list. When I try to do this, AMSMB2 returns "socket is not connect"

Could you please help me?

pod 'AMSMB2'

NSURLCredential *credential = [[NSURLCredential alloc]initWithUser:userName password:passWord persistence:(NSURLCredentialPersistenceForSession)];
                    
            NSString *url = [NSString stringWithFormat:@"smb://192.168.1.123"];
                        
            if (self.smb2 == nil) {
                
                self.smb2 = [[AMSMB2 alloc]initWithUrl:[NSURL URLWithString:url] domain:@"WORKGROUP" credential:credential];
            }

 [self.smb2 listSharesWithEnumerateHidden:YES completionHandler:^(NSArray<NSString *> * _Nonnull files, NSArray<NSString *> * _Nonnull arry, NSError * _Nullable error) {

}];

[self.smb2 connectShareWithName:@"music_sync" completionHandler:^(NSError * _Nullable error) {
                                    
                    NSLog(@"error :  %@",error);
                }];

**Comment by amosavian** [comment]
Please use latest version using Swift Package Manager, Cocoapod version is not supported anymore.
