### ISSUE TITLE
Dependency "AMSMB2" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by thanhthuc** [amosavian/AMSMB2#102]
Hi Amosavian,

I have build AMSMB2 xcframework with Carthage again and there was an error with latest version 3.3.1:
Skipped building AMSMB2 due to the error:
Dependency "AMSMB2" has no shared framework schemes for any of the platforms: iOS

Can you help me solve this issue, 

Thank you!

**Comment by amosavian** [comment]
Please only use SPM to add AMSMB2 to your project. All other dependency managers are unsupported.
