### ISSUE TITLE
Using to stream AV files....

### ISSUE THREAD

**Issue by lechium** [amosavian/AMSMB2#103]
First and foremost thank you for this library, upon cursory glance it works very nicely and was very easy to set up. One thing I can't determine is it possible to leverage this project to stream AV files from the SMB shares without downloading them first? If so, please provide an example of how this is possible.

Thanks!

**Comment by amosavian** [comment]
Thanks.

It should be possible to fetch given byte range of file using `contents(atPath:range:progress:)` method.

If you are developing an iOS/macOS application. you may implement [`AVAssetResourceLoaderDelegate`](https://developer.apple.com/documentation/avfoundation/avassetresourceloaderdelegate) to allow streaming. It gives the offset and length to download. There are plenty of examples on how to use it.
