### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by sqruirrel** [amosavian/AMSMB2#105]
Hi, I am using OC . I have just introduced AMSMB2 using SPM and encountered this error after building it.  I don't know how to use Swift, so what should I do?  😥
<img width="1676" alt="Xnip2024-05-10_09-19-43" src="https://github.com/amosavian/AMSMB2/assets/29775957/930295f5-d333-4f86-8b8e-ef7dbb2d8bb4">

**Comment by amosavian** [comment]
Please use Swift 5.9 or 5.10 to build.

**Comment by sqruirrel** [comment]
Thanks for your reply! And I'm sorry to bother you, I have upgraded Swift to 5.10, but it crashes as soon as I run the application. I haven't used SPM before，so I'm not sure what the problem is
<img width="1312" alt="Xnip2024-05-13_18-40-58" src="https://github.com/amosavian/AMSMB2/assets/29775957/2c84b6f2-b5db-4eeb-b129-462ebccdc942">
