### ISSUE TITLE
Doesn't compile with Xcode 16 SDK

### ISSUE THREAD

**Issue by RuiNelson** [amosavian/AMSMB2#109]
Normally can't compile libsmb2 with Xcode 16 (beta).

I would submit a PR to your libsmb2 fork, but I can't fork, modify, PR the specific commit you're using.

All it's needed is to add

    #include <time.h>

to `smb2.h`

And

    #include <stddef.h>

to `libsmb2.h`

Thank you

**Comment by vdkdamian** [comment]
Same issue here. Don't know about the solution.

**Comment by XuWeinan123** [comment]
same issue... I have to use old version of Xcode to code my project.
Hope apple to fix it quickly.

**Comment by XuWeinan123** [comment]
emm...build success, but project broken when run
<img width="1352" alt="Screenshot 2024-08-04 at 2 10 36 PM" src="https://github.com/user-attachments/assets/a85f6340-cfe3-485d-bb1f-bb4c09b748b0">

**Comment by blendstylez** [comment]
same here...i would really appreciate you fixing this small issue asap - thx in advance

**Comment by erikbernsen** [comment]
Same issue here.

**Comment by amosavian** [comment]
It's fixed in 3.4.0

**Comment by erikbernsen** [comment]
Thanks. Will try it today.
