### ISSUE TITLE
Update AMSMB2 Version in CocoaPods to Latest Version

### ISSUE THREAD

**Issue by suraj727785** [amosavian/AMSMB2#114]
The current version of AMSMB2 in the cocopods is still  2.7.1. However, there have been newer releases of AMSMB2 that include important updates and bug fixes. Please update the version in the cocoapod to the latest stable release of AMSMB2 to ensure the project benefits from the latest features, optimizations, and fixes.

**Comment by amosavian** [comment]
Cocoapods support is dropped due to complicated building. It is possible to use SPM and Cocoapods simultaneously.
