### ISSUE TITLE
With Kerberos support

### ISSUE THREAD

**Issue by debugly** [amosavian/AMSMB2#115]
I can't find with-krb5 option after use swift package manager, is supported by default?
I want to know how to build libraries with Kerberos support?

**Comment by amosavian** [comment]
Kerberos is not supported currently in libsmb2 on Apple platforms, thus I did not enabled it. To activate it, the proper flag should be set in `Package.swift`.

**Comment by debugly** [comment]
Hi amosavian, is libsmb2 smb2_read_async  is faster than smb2_read ? on tvOS,my demo use smb2_read is very slow, i don't why? can you help me?

**Comment by debugly** [comment]
I found that it is related to the size of the buffer used when reading and has nothing to do with synchronous or asynchronous APIs.
