### ISSUE TITLE
Memory leak in AMSMB2 3.4.0

### ISSUE THREAD

**Issue by erikbernsen** [amosavian/AMSMB2#116]
I'm reading a lot of files with 3.4.0 and see a memory leak. Could also be a memory leak in underlying libsmb. Previous version didn't have this issue. If needed I can try to create a small sample program to reproduce the problem.

<img width="1055" alt="memoryleak" src="https://github.com/user-attachments/assets/563ac82f-59ce-4a10-8c32-456793e5d9c6">
<img width="818" alt="stacktrace" src="https://github.com/user-attachments/assets/0eaf14e2-36d3-40e7-bc42-3b2206d38469">

**Comment by amosavian** [comment]
This method (`smb2_process_read_variable`) is defined in [libsmb2](https://github.com/sahlberg/libsmb2). it's appreciated if you open an issue directly on `libsmb2` repository.

**Comment by erikbernsen** [comment]
I'm taking a look at this. Trying to understand if it's AMSMB2's responsibility to free this memory or libsmb2. In the mean time I created a very small program to reproduce the problem, just to make sure the issue is not in my own code. See attached. 
[Archive.zip](https://github.com/user-attachments/files/17350139/Archive.zip)

**Comment by erikbernsen** [comment]
The issue was indeed with libsmb2 and is fixed now. When can you @amosavian include this fix in a amsmb2 rekease?

**Comment by amosavian** [comment]
Hi, unfortunately there was an issue in opendir and closedir memory management and it took time to find a workaround.

This problem should be fixed in version 4.0.0
