### ISSUE TITLE
Connection failure, how to handle it

### ISSUE THREAD

**Issue by jazzforlove** [amosavian/AMSMB2#117]
private func connect(handler: @escaping (Result<AMSMB2, Error>) -> Void) {
            // AMSMB2 can handle queueing connection requests
            client.connectShare(name: self.share) { error in
                if let error = error {
                    handler(.failure(error))
                } else {
                    handler(.success(self.client))
                }
            }
        }
Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc00000cc) STATUS_BAD_NETWORK_NAME. }

**Comment by amosavian** [comment]
This means share name is invalid. You can find more information in https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/652e0c14-5014-4470-999d-b174d7b2da87
