### ISSUE TITLE
How can I get the list of root directory?

### ISSUE THREAD

**Issue by yuchigit** [amosavian/AMSMB2#12]
I can't use it  by this way 
`connectShare(name:"")`. It didn't work. 

And this way too...
```
client.contentsOfDirectory(atPath: "",
               completionHandler: {
```

I need get a list of current directory or root.

**Comment by yuchigit** [comment]
I had solved this question. There is a method called `listShares`

**Comment by amosavian** [comment]
There is no root directory in SMB. You have shares and you **must** know share name to connect. Assuming you mean listing shares, you can use `listShares` method to get the list, even before calling `connectShare` method.
