### ISSUE TITLE
smb2_rewinddir crash

### ISSUE THREAD

**Issue by charsdavy** [amosavian/AMSMB2#123]
<img width="2398" alt="截屏2024-11-12 18 17 12" src="https://github.com/user-attachments/assets/4fe0aca7-46bf-4eae-b64b-d1c7c31582a2">

When using the contentsOfDirectory method to quickly retrieve the contents of a folder within a short period of time, a crash issue similar to the one shown in the above image occurs.

**Comment by amosavian** [comment]
This is a bug in libsmb2, not AMSMB2, however I tried to implement a workaround for that in 4.0.1 which works for most of cases but not all.
Please open an issue in https://github.com/sahlberg/libsmb2 directly to fix this.

**Comment by erikbernsen** [comment]
I was running into similar issues on a previous version of AMSMB2. Trying to reproduce it on latest version without success. So indeed the workaround does something. I see this code in Directory.swift:

![image](https://github.com/user-attachments/assets/c154229c-1f8e-4057-af34-43f188dce6e1)

Is this while-loop the workaround you're talking about??? Trying to understand this so I can fix it.

**Comment by erikbernsen** [comment]
Created this issue on libsmb2 https://github.com/sahlberg/libsmb2/issues/382

**Comment by amosavian** [comment]
@erikbernsen yes that's it. It seems libsmb2 has fixed it now so I can remove that code soon
