### ISSUE TITLE
SMB Write cases failed on synology smb server.

### ISSUE THREAD

**Issue by kasimok** [amosavian/AMSMB2#17]
Hi Amosavian,
  I downloaded your project, I ran your test cases, and for some smb servers the test cases all passed. But when I test it over a samba share from Synology NAS, write related cases raises "Inconsitency in writing to SMB file handle." error. You mentioned " Data saved in server maybe truncated when completion handler returns error." in the API. So you have any idea how to handle this?
Thanks

**Comment by amosavian** [comment]
My test devices are my mac and a Western digital MyCloud network device I've obtained, which is technically a samba server.

I don't know what goes wrong with Synology. I recommend you to add a breakpoint [on this line](https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/AMSMB2.swift#L956) and investigate what's the result of underlying `write` function.

**Comment by kasimok** [comment]
Thanks for the response.
 Looks like the written count(61440) does not equal to segment count(65536)
![image](https://user-images.githubusercontent.com/5194603/48874023-ed79ff80-ee2b-11e8-8c68-28289294453f.png)
Inspired by an [issue](https://github.com/sahlberg/libsmb2/issues/43) in libsmb2 from you, I changed the optimizedWriteSize to a smaller number, the error is gone.  
`    var optimizedWriteSize: Int {
        return min(maxWriteSize, 32*1024)
//        return min(maxWriteSize, 1024*1024)
    }`
And strange thing is that writing to other smb servers appears to be OK with the default 1MiB size. All synology smb servers fails(I have 2 synology smb server).

**Comment by amosavian** [comment]
Yes, this is a known issue. Reducing write size would decrease transfer speed dramatically.
