### ISSUE TITLE
Download item with path having spaces

### ISSUE THREAD

**Issue by HosamShawky** [amosavian/AMSMB2#19]
Currently I’m facing an issue with downloadItem as follows:
 
I connect to server.                                         192.xxx.xxx.xxx
I connect to a share.                                       shareName
List share                                                            Share1, share2, Share3
List directory for lets say share1.               dir1, dir 2, dir3.  “see the space in dir 2”  
List of files are displayed                               file1, file 2, file 3
When I try to downloadItem  using atPath: “dir 2/file1” an error is returned “No such file or directory”
While trying to do the same with a directory name that has no spaces works fine.
I tried the following for directory name:
Change dir 2 to dir\ 2         so the atPath would be dir\ 2/file1       
Change dir 2 to dir%202    so the atPath would be dir%202/file1  
Change dir 2 to “dir 2”       so the atPath would be “dir 2”/file1        also tried “dir 2/file1”

**Comment by amosavian** [comment]
You should not add any escaping to path. Something like this should work perfect:

```swift
"/dir 2/file1"
```

**Comment by HosamShawky** [comment]
This is the error I get for downloading the following:
/Sharm Sep-2013/20130910_162659.jpg

Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedFailureReason=Error code 22: }

while downloading
/Malaysia/Mal 001.jpg 
Works fine

**Comment by HosamShawky** [comment]
/ in the beginning didn't work, but it seems that escaping the destination url was the problem.

Thanks for the answer
