### ISSUE TITLE
Error for creationDateKey

### ISSUE THREAD

**Issue by skrew** [amosavian/AMSMB2#2]
https://github.com/amosavian/AMSMB2/blob/b1a7a2ada8a54a61ed980b30f09bf21f5088aa7b/AMSMB2/AMSMB2.swift#L796

It's creation time, not modification time :)

**Comment by amosavian** [comment]
Good point! 

As a bonus I will add `.contentAccessDateKey`, `.linkCountKey` and `.documentIdentifierKey` keys.
