### ISSUE TITLE
SMB connection version negotiated

### ISSUE THREAD

**Issue by MynaBay** [amosavian/AMSMB2#21]
Is there a way to detect the SMB connection version that was negotiated? I tried using SMBContext's Version but it's returning Any. That is fine before the connection is made, but after it connected reporting what was negotiated seems appropriate.

**Comment by amosavian** [comment]
This type is imported directly from C (typealias for `smb2_negotiate_version`) and is populated by libsmb2 directly. I don't have any control over it.
