### ISSUE TITLE
Test case 'testShareEnum' fails on Xcode10.2

### ISSUE THREAD

**Issue by kasimok** [amosavian/AMSMB2#22]
Hi Amosavian
    The test case `testShareEnum` failed on latest XCode. Can you have a try?
   PS. I recompiled the libsmb2 with your build script, and the issue is the same.

**Comment by fabiosoft** [comment]
Same here. The method while getting the share list, hangs...and after a very long timeout nothing is returned. Testing with Xcode 10.1 everything works.

**Comment by kasimok** [comment]
@fabiosoft : The author already replied me in libsmb2 repo. See this: [libsmb2 issue](https://github.com/sahlberg/libsmb2/issues/81), I reverted build tool to XCode 10.1 as a workaround.

**Comment by fabiosoft** [comment]
Do you mean `Command Line Tools` dropdown menu in Xcode's preferences > location?

**Comment by kasimok** [comment]
@fabiosoft I mean downgrade Xcode to 10.1 and use it to build app. Everything goes well.

**Comment by amosavian** [comment]
@fabiosoft @kasimok Fixed, please. update.
