### ISSUE TITLE
Error on downloadItem into temp directory

### ISSUE THREAD

**Issue by odin321** [amosavian/AMSMB2#26]
Hi, thank you for this library, really helpful to me.

However I encounter an issue when I want to download Item from my Shared Folder into my temporary directory in iOS using Swift 4.2 and XCode 10.2.

**This is how I create the temp directory URL :**
`let tempURL = URL(fileURLWithPath:NSTemporaryDirectory()).appendingPathComponent(fileName)`

**The value of tempURL will be :** 
file:///Users/odin321/Library/Developer/CoreSimulator/Devices/F459303B-A4FD-494F-A437-F7EF57384FDD/data/Containers/Data/Application/21857A2A-9035-4856-9A12-6B78A79139A6/tmp/file%20Name.csv

Everything went well, I could download the item successfully, but when I use **same tempURL with another fileName**, often the process will fail with error : 
Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory" UserInfo={_kCFStreamErrorCodeKey=20, _kCFStreamErrorDomainKey=1} 
or
Error Domain=NSPOSIXErrorDomain Code=21 "Is a directory" UserInfo={_kCFStreamErrorCodeKey=21, _kCFStreamErrorDomainKey=1} 

At the moment I just drop the last path component from the URL using `tempURL.deletingLastPathComponent()` if the error occured, and the item will be downloaded.

I'm not sure if this is correct approach , or was I writing the temp directory wrong ?

Thank you in advance.

**Comment by amosavian** [comment]
Si have no idea why you get CFStreamError in SMB2 while I sis not use streams.

**Comment by amosavian** [comment]
I have no idea what's happened. But error messages are clear. You are either trying pass a directory path when library expects a file path or vice versa.

I use `Stream`s to write and read locale files as you can find in [this line](https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/AMSMB2.swift#L818). Putting a breakpoint here may help you to find underlying error by investigating passed url and cheking file existence using `FileManager` methods

**Comment by odin321** [comment]
Thank you for the response, turns out the my fileName variable is sometimes an empty string value (""). 

For now I'll just make sure it wont be empty and close this issue as well.
