### ISSUE TITLE
Connect / contentsOfDirectoryAtPath fail on Xcode10.2.1 (iOS 11/12)

### ISSUE THREAD

**Issue by fabiosoft** [amosavian/AMSMB2#28]
The method while connecting or trying to get contents listing (I assume because it's never reached), **hangs**...and after a very long timeout no completion is called and nothing is returned. If in my code a execute again it crashes on `bindMemory` method.

How can I solve? I need latest Xcode version to support iOS12.

I already updated to latest (2.0) git release
Tested on with Xcode 10.1 (AMSMB v1.7.0) everything works. I cannot test the latest due to swift 5.0 compatibility

**Comment by amosavian** [comment]
Please run tests on your computer. You must change server address and share name in tests.

**Comment by fabiosoft** [comment]
You are free to not believe but tests pass but in a project it hangs and stop and no completion is ever called...

Sometimes it crashes on this line in `Context.swift`

<img width="1390" alt="Schermata 2019-06-28 alle 17 03 16" src="https://user-images.githubusercontent.com/812037/60352414-149f3d80-99c8-11e9-9d6c-e02f8a798e5c.png">

**Comment by fabiosoft** [comment]
Also...how is possibile that with the same code on Xcode10.1 works perfectly and with latest version all is broken?

**Comment by amosavian** [comment]
It's not about believing or not, I should be able to reproduce the exact issue in order to debug. Please create a sample project at least.

**Comment by fabiosoft** [comment]
I prepared a sample and systematically every time timeout expires I get `EXC_BAD_ACCESS`
Let me know if there is a mistake or an issue

Thanks so much

[sample_smb.zip](https://github.com/amosavian/AMSMB2/files/3344788/sample_smb.zip)

**Comment by fabiosoft** [comment]
Any news?

**Comment by emilhornlund** [comment]
I have the same problem. However, the problem does not appear to be in `listFolderContents` but in `listShares` where the crash actually occurs, eventually after the timeout. It is not a huge problem as it only occurs in the simulator. At least in my case. When I have more time I will do more thorough testing.

**Comment by fabiosoft** [comment]
@emilhornlund that's very interesting, what's your environment? Xcode/iOS version?

**Comment by emilhornlund** [comment]
macOS 10.14.5, Xcode 10.2.1, Simulator 12.2, iPhone 12.1.2

**Comment by fabiosoft** [comment]
i'll try it out

**Comment by fabiosoft** [comment]
@emilhornlund i have some updates: 

- Ok on macOS 10.14.5, Xcode 10.2.1, iPhone 12.3.1 
- Not working on macOS 10.14.3, Xcode 10.2.1, iPhone 12.x
- On simulator only works if using Xcode 10.1 and AMSMB v 1.7.x, otherwise crash every timeout.

I tried samba server hosted on macOS 10.14, and 10.13 no difference.
I think something changes during build....but what? @amosavian do you have any ideas?

**Comment by amosavian** [comment]
Hi, I'm busy on deadlines right now. I shall investigate but it appears it is an issue in Swift runtime on specific version.
`listShares` has two versions internally. Would you mind check if `_swift_listShares` function works in tests or not? If it works, I can fallback to that implementation in these problematic versions.

**Comment by Stermop** [comment]
I have the same problem, crash happens in any possible situation, not just in simulator or specific macOS version. Is there a solution?
