### ISSUE TITLE
Session setup failed with (0xc00000be) Unknown.

### ISSUE THREAD

**Issue by mstolin** [amosavian/AMSMB2#3]
Hey,

at first thanks for this nice lib.

Can you help me with a problem, create a connection to my smb server?

For development i activated the File sharing functionality on my mac, so my address is a local ip `smb://192.168.0.xxx` and my login credentials are the same as on my mac.

This is how i try to connect to my local smb server.
```swift
class SMBConnection {
    
    func connect(handler: @escaping (_ client: AMSMB2?, _ error: Error?) -> Void) {
        let credential = URLCredential(user: "User", password: "MyPassword", persistence: .forSession)
        let client = AMSMB2(url: URL(string: "smb://192.168.0.xxx")!, credential: credential)!
        client.connectShare(name: "MYSHARE") { error in
            handler(client, error)
        }
    }
}
```
```swift
let conn = SMBConnection()
conn.connect { (client, error) in
            if let error = error {
                print(error)
                return
            }

            print("WORKED !!")
        }
```

So when i try this i always get the error `Error Domain=NSPOSIXErrorDomain Code=5 "Input/output error" UserInfo={NSLocalizedFailureReason=Error code 5: Session setup failed with (0xc00000be) Unknown. }`. It happens on my simulator and on my device (while its connected to the local network, other third party apps can connect to my smb server).

Thanks in advance :)

**Comment by amosavian** [comment]
Ate you sure you server supports SMB2?

**Comment by mstolin** [comment]
After a little of research it seems that mac os is using smb3 (im on macOS High Sierra 10.13.5).

**Comment by amosavian** [comment]
Aha you turned your mac into server? smb3 is a dialect of smb2.

I have no issue with connecting to my mac.

Would you mind execute `listShares()`` functions to see if it works or not?

**Comment by mstolin** [comment]
So
```
client?.listShares(enumerateHidden: false, completionHandler: { (names, comments, error) in
    print(names)
    print(comments)
    print(error)
})
```

Prints out
```
["Marcel Stolins öffentlicher Ordner"] // Thats actually the name of my shared folder
[""]
nil
```

So there has to be a connection at sometime.

**Comment by amosavian** [comment]
Please check this code, which share name is included in url:

```swift
let credential = URLCredential(user: "User", password: "MyPassword", persistence: .forSession)
let client = AMSMB2(url: URL(string: "smb://192.168.0.xxx/MYSHARE")!, credential: credential)!
client.connectShare(name: "MYSHARE") { error in
    handler(client, error)
}
```

**Comment by mstolin** [comment]
Its working now 👍 

```
client.listShares(enumerateHidden: false, completionHandler: { (names, comments, error) in
    if let error = error {
        handler(client, error)
    }
            
    client.connectShare(name: names.first!) { error in
        handler(client, error)
    }
})
```

I was also able to run `conn.listDirectory(path: "/")` with the correct results.
Thanks so much for help :)

**Comment by amosavian** [comment]
I couldn’t understand what was the problem. Would you describe me what solved the issue?

**Comment by mstolin** [comment]
At `client.connectShare(name: "MYSHARE")` i was trying to connect to the share `MYSHARE` which doesnt exists. `client.listShares` told that i have only one share which has a complety different name so i connected to the first share of my shares `client.connectShare(name: names.first!)`.

**Comment by amosavian** [comment]
Aha okay
