### ISSUE TITLE
EXC_BAD_ACCESS on line `cbdata.data = command_data`

### ISSUE THREAD

**Issue by Jeehut** [amosavian/AMSMB2#31]
When using AMSMB2 2.2.0 within Xcode 11 beta 3 in a project which always worked before, without changing any code, after updating to AMSMB 2.2.0 from 2.0.0, I'm now getting this crash:

<img width="1680" alt="Bildschirmfoto 2019-07-05 um 15 37 17" src="https://user-images.githubusercontent.com/6942160/60726168-33a74d80-9f3b-11e9-96ab-347be04689eb.png">

**Comment by amosavian** [comment]
I think this is similar to #28, please follow that thread.

**Comment by Dschee** [comment]
Thanks for the pointer, I saw that but I wasn't sure if it's really the same issue. Feel free to close if you believe it is. In any case, I just downgraded to version 2.0.0 and the issue seems to be gone.
