### ISSUE TITLE
How to link this library dynamically to app

### ISSUE THREAD

**Issue by srinadh-k** [amosavian/AMSMB2#36]
Hi,

We have used this pod today and seems it matches our requirements. But we worried about, Will AppStore approve or not?

Please let us know, How to link this library dynamically to our app for AppStore review?

Thank you for your efforts to make this great library.

**Comment by amosavian** [comment]
If you use Cocoapods then you must use `use_frameworks!` in your pod file.

Otherwise follow instructions provided in [install section](https://github.com/amosavian/AMSMB2#install)
