### ISSUE TITLE
Header 'AMSMB2-Swift.h' not found

### ISSUE THREAD

**Issue by goolai** [amosavian/AMSMB2#39]
There're issues with this library when run in Xcode 10 with Swift 4. Some of issues I could fix by myself, but there're issues I can't fix:
```Header 'AMSMB2-Swift.h' not found```

Do you have idea how to fix this issue?

**Comment by amosavian** [comment]
Hi,

This library is using Swift 5. In case you need to maintain your main project in Swift4, please use package managers like Cocoapods

**Comment by brandonrains77** [comment]
I Have just added your project via SPM and when I imported it into my project it says 'no such module AMSMB2' 
Any Idea what it could be ?

![screenshotsmudged](https://user-images.githubusercontent.com/56743230/67134907-5273dc00-f1da-11e9-938f-cd561fa2d57d.png)

**Comment by brandonrains77** [comment]
Here is some more info on what will cause this problem:

STEPS TO REPRODUCE
1)Make a new project, Single view app
2) FIle > Swift packages > Add Package Dependancy > Paste this in search bar "https://github.com/amosavian/AMSMB2.git" Next > select Branch : master > Finish
3) Press build

Throws the swift compiler error:
No such module "SMB2" 
AMSMB2.swift

**Comment by amosavian** [comment]
This library embeds pre-compiled binaries hence does not support SPM. That `Package.swift` is there to support Accio package manager.

I must remove that file in order to prevent such mistakes.

**Comment by brandonrains77** [comment]
Thanks for the quick reply! I am new to all this, but if I can't use SPM to add your work to my project, what are the steps to add it? I am using xcode 11 and using swift 5

**Comment by brandonrains77** [comment]
I am not using the SPM, But now a workspace added with AMSMB2 but when I build it says "No such module 'AMSMB2'

Any ideas how to get this to build?

**Comment by goolai** [comment]
> Hi,
> 
> This library is using Swift 5. In case you need to maintain your main project in Swift4, please use package managers like Cocoapods

thanks for the support.

**Comment by Jeehut** [comment]
@amosavian SwiftPM does support binary artifacts, so I think this is solvable by now. See SE-0272 for more details:
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md#proposed-solution

**Comment by Jeehut** [comment]
I believe this can be fixed now thanks to [SE-0272](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md#proposed-solution), but I have no experience with static C libraries so I would need to invest a lot of time to get this working. I found [this thread](https://forums.swift.org/t/packaging-static-library-in-spm-package-for-ios-executable/41245/1) on the Swift forums though which might help.

**Comment by amosavian** [comment]
Please use version 3.0.0
