### ISSUE TITLE
Can't install via Cocoapods - Not Found

### ISSUE THREAD

**Issue by anonymouz4** [amosavian/AMSMB2#4]
It says `[!] Unable to find a specification for "AMSMB2"`

**Comment by amosavian** [comment]
I’ve checked `pod try AMSMB2` without issue

Please check https://cocoapods.org/pods/AMSMB2 for more information

**Comment by anonymouz4** [comment]
No doesn't work. Tried with '' and ""

**Comment by anonymouz4** [comment]
Ok, now it suddenly works, even though I ran the same command, strange
