### ISSUE TITLE
Trying to list directory

### ISSUE THREAD

**Issue by DDavis1025** [amosavian/AMSMB2#40]
Right now I'm trying to just list the directory and get this error:

Error Domain=NSPOSIXErrorDomain Code=5 "Input/output error" UserInfo={NSLocalizedFailureReason=Error code 5: Session setup failed with (0xc00000be) Unknown. }

I haven't put in a share name for my project because I don't know what I'm sharing and or how? I'm trying to build an app that can view files from my Mac or PC and download them to my app. What do I have to do to complete this process?

Thanks

**Comment by amosavian** [comment]
Hi,

I think this problem is related to libsmb2. Soon I will bundle a new build of that which I guess fixes this issue.

**Comment by amosavian** [comment]
Check out version 2.3.0
