### ISSUE TITLE
EXC_BAD_INSTURCTION (code=EXC_I386_INVOP,subcode=0x0)

### ISSUE THREAD

**Issue by srinadh-k** [amosavian/AMSMB2#41]
Hi facing EXC_BAD_INSTURCTION crash sometimes. Please see the attached image. 
![Screen Shot 2019-11-05 at 10 13 27 AM](https://user-images.githubusercontent.com/28667119/68224901-1c45a300-ffb5-11e9-9578-bf18f33d1797.png)

**Comment by amosavian** [comment]
This is a bug in libsmb2. I'll made a workaround to fix this. Though I'm not sure it can be fixed as I can't reproduce it.

**Comment by srinadh-k** [comment]
Thank you for your response, today also got one more crash. seems when we do some concurrency operations. we are getting crash issue. 
<img width="1401" alt="Screenshot 2019-11-06 at 12 27 53 PM" src="https://user-images.githubusercontent.com/28667119/68326379-ef66be00-0090-11ea-8d86-e45982912309.png">

**Comment by srinadh-k** [comment]
If you fix it and share with us, we will let you know. we have been getting this issue.

**Comment by amosavian** [comment]
Can I ask which version of Xcode are you using?

**Comment by srinadh-k** [comment]
It is Xcode 11.1

**Comment by venkatraor** [comment]
> Hi facing EXC_BAD_INSTURCTION crash sometimes. Please see the attached image.
> ![Screen Shot 2019-11-05 at 10 13 27 AM](https://user-images.githubusercontent.com/28667119/68224901-1c45a300-ffb5-11e9-9578-bf18f33d1797.png)

I am also facing same kind of issue. Seems like issue in SMB library.

**Comment by amosavian** [comment]
It would be great if anyone can write a test case which reproduces this error.

**Comment by srinadh-k** [comment]
Here is my test case: 

calling connectShare method every 30 seconds to establish or check Connection with "smb".
Our app runs 24*7 in background and foreground. So after couple of hours later we are getting crash.

**Comment by amosavian** [comment]
This is not a test case. A method must be added to https://github.com/amosavian/AMSMB2/blob/master/AMSMB2Tests/AMSMB2Tests.swift to replicate this issue

**Comment by amosavian** [comment]
I finally found out that the problem is in `smb2->outqueue`, where pdu->cbdata is probably is overreleased.

I will try to handle this.

**Comment by srinadh-k** [comment]
Thank you

**Comment by srinadh-k** [comment]
Lets us know, when you done, so we can update our pod file.

**Comment by amosavian** [comment]
This issue should be solved by now. If you still have problems, please open a new issue
