### ISSUE TITLE
Build error occured

### ISSUE THREAD

**Issue by geysee** [amosavian/AMSMB2#42]
Hi,

There are occured a build error where line 56 in Extensions.swift .
The error message is following.

> The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

![build_error](https://user-images.githubusercontent.com/3407398/68279637-310a5f80-00b7-11ea-9f9a-6ebf131ab527.png)

My development environment is following.
 - Swift ver.5
 - xcode ver.10.2.1(10E1001)
 - macOS Mojave ver.10.14.5

I could fix the error by changing the code to:

```
    mutating func append(value: UInt64) {
        let value1 = UInt8(value & 0xff)
        let value2 = UInt8(value >> 8 & 0xff)
        let value3 = UInt8(value >> 16 & 0xff)
        let value4 = UInt8(value >> 24 & 0xff)
        let value5 = UInt8(value >> 32 & 0xff)
        let value6 = UInt8(value >> 40 & 0xff)
        let value7 = UInt8(value >> 48 & 0xff)
        let value8 = UInt8(value >> 56 & 0xff)
        self.append(contentsOf: [value1, value2, value3, value4, value5, value6, value7, value8])
    }
```

Please change the code.

Best regards,

**Comment by amosavian** [comment]
You ae using an old version of AMSMB2, please update to latest version.

**Comment by geysee** [comment]
Thank you for your reply.
I'm sorry, it was my problem.

I got ver.1.7.0 with cocoa pods.
It seems that latest version is 2.4.0.

Could you tell me how to get the latest version 2.4.0 with Cocoa pods?
I tried following configuration.

Profile

> pod 'AMSMB2'

command

> pod install

Best Regards,

**Comment by amosavian** [comment]
Check your pod file to ensure AMSMB2 is not pinned to old version, then execute "pod update".

**Comment by geysee** [comment]
Thank you for your reply.

I'll try review the cocoapods settings and report the results again.
Thank you.

**Comment by geysee** [comment]
Hi,

I could upgrade from version.1.7.0 to 2.4.0 with "pod update".
Thank you.

However, another build error occuerd.

> Use of unresolved identifier 'Self'

![BuildError_Self](https://user-images.githubusercontent.com/3407398/68361894-d03b5f80-0168-11ea-9c60-9257c1818e69.png)

My application support iOS 10.0 later. Is this affecting?

Could you tell me how to fix, if you know.

Best Regards,

**Comment by geysee** [comment]
I have the build error with just AMSMB2 ver.2.4.0.
No build error with AMSMB2 ver.2.3.1.

**Comment by amosavian** [comment]
`Self` is added in Swift 5.1. You must use Xcode 11 to build.

**Comment by geysee** [comment]
The "Self" build errors have cleared with Xcode 11.2.

Thank you very much for your quick response 😃
