### ISSUE TITLE
How to detect any devices on the local network with a  NetBIOS name

### ISSUE THREAD

**Issue by sunsx9316** [amosavian/AMSMB2#43]
Like [TOSMBClient](https://github.com/TimOliver/TOSMBClient), I can find SMB devices by `TONetBIOSNameService`. Can AMSMB2 do this?

**Comment by amosavian** [comment]
NetBIOS is obsolete. This library and the underlying libsmb2 do not support nor will implement obsolete protocols. Read more [here](https://github.com/sahlberg/libsmb2/issues/70). Pure SMB2 servers also do not support NetBIOS.

You can use Zeroconf/Bonjour to discover servers. Apple provides functionality  `NetServiceBrowser` class.
