### ISSUE TITLE
If the gracefully argument of disconnectShare is set to true, no response is returned

### ISSUE THREAD

**Issue by geysee** [amosavian/AMSMB2#44]
Hi, 

If the "gracefully" argument of disconnectShare() is set to true, no response is returned.

If I use AMSMB2 frequently, my app may terminated, so I feel I need to make the disconnectShare() argument "gracefully" true.

Looking at AMSMB2.swift, disconnectShare () itself increments operationCount, so it seems that disconnectShare () keeps waiting without oeprationCount becoming 0.

I think 240 lines should be as follows.

`while self.operationCount> 1`

Best Regard,

**Comment by amosavian** [comment]
Your conclusion seems reasonable. I will check.

**Comment by geysee** [comment]
After changing the code to “while self.operationCount> 1”, I repeatedly tested the disconnectShare () function with “graceful = true”.

As a result, the app may still terminate.

<img width="1280" alt="Thread52_0" src="https://user-images.githubusercontent.com/3407398/71242459-601c1e00-2351-11ea-87e8-03e1f291bd5e.png">

put images of the call history when the app was terminated in zip file.

[callHistory.zip](https://github.com/amosavian/AMSMB2/files/3987556/callHistory.zip)

My app calls connectShare () and disconnectShare () before and after a series of SMB processing.
Is this method not preferable?

**Comment by geysee** [comment]
Hi,

Always thank you for your help.

There is the following comment in the connectShare () function:

> Workaround disgraceful disconnect issue (e.g. server timeout)

My app may also terminate on SMB timeout.
Could you know the reason?

Looking at the code for the connectShare () function, it seams that it is safe for the app to call connectShare () continuously without calling disconnectShare ().

If connectShare () supports timeout problem, is it better not to call disconnectShare () basicaly?

Please help me.
Best Regards,

**Comment by amosavian** [comment]
Use this code instead of yours for disconnect and tell me if it works

```swift
    open func disconnectShare(gracefully: Bool = false, completionHandler: SimpleCompletionHandler = nil) {
        q.async {
            do {
                self.connectLock.lock()
                defer { self.connectLock.unlock() }
                if gracefully {
                    self.operationLock.lock()
                    while self.operationCount > 0 {
                        self.operationLock.wait()
                    }
                    self.operationLock.unlock()
                }
                try self.context?.disconnect()
                self.context = nil
                completionHandler?(nil)
            } catch {
                completionHandler?(error)
            }
        }
    }
```

**Comment by amosavian** [comment]
Technically it is safe not to call `disconnect()` method as it will be called on release any way. But when you release the variable, any ongoing job will be terminated. This method provides a way to ensure any ongoing job will be done before releasing if your cleaning code is placed inside completion handler.

**Comment by geysee** [comment]
Thank you vary much for your reply code !
I will try !

**Comment by geysee** [comment]
> Technically it is safe not to call disconnect() method as it will be called on release any way. But when you release the variable, any ongoing job will be terminated. This method provides a way to ensure any ongoing job will be done before releasing if your cleaning code is placed inside completion handler.

I tried without disconnectShare(). But my app terminated.

<img width="1279" alt="terminatedWithoutUsingDisconnectShare" src="https://user-images.githubusercontent.com/3407398/71247571-5f3cb980-235c-11ea-9111-d703fe3e7a2f.png">

It is not using your new code.
I will continue to try your new code.

**Comment by geysee** [comment]
I tested your code.
But unfortunately my app is still terminated.

I tried using a network emulator to cause network delays.
Then, the termination of my app was reproduced immediately.

I will try to emulate it with the debugger connected.
And I will provide you to information.

I hope you continue to provide me your test code.

Best Regards,

**Comment by amosavian** [comment]
I have a guess on why app crashes. It is not related to disconnection.

**Comment by amosavian** [comment]
Please comment this line to see if the problem persists:

https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/Context.swift#L194

**Comment by geysee** [comment]
Sorry, the emulation that terminated my app was a packet loss, not a delay.
I tried it with debugger.

![terminatedWithPacketLoss](https://user-images.githubusercontent.com/3407398/71253186-7d111b00-236a-11ea-887e-03635ecb2d45.png)

Thank you for your next code.
I will try it.

**Comment by geysee** [comment]
I tried comment outed code.
https://github.com/amosavian/AMSMB2/blob/master/AMSMB2/Context.swift#L194

However, my app  terminated at the same point.

![terminatedWithPacketLoss2](https://user-images.githubusercontent.com/3407398/71254094-3670f000-236d-11ea-8315-ed52d8243ff0.png)

Please next code change.

**Comment by geysee** [comment]
I attached a call stack images in zip when my app terminated.

[callstackWhenTerminatedWithPacketLoss.zip](https://github.com/amosavian/AMSMB2/files/3988377/callstackWhenTerminatedWithPacketLoss.zip)

I'm sorry, my next response will be 12/23.

Best Regards,

**Comment by geysee** [comment]
Hi, I'm back.

Do you have any progress?

**Comment by geysee** [comment]
Hi,

New information.

My app is setting timeout which is at line 26 in AMSMB2.swift to 30 sec.

When timeout is 60 sec which is deafault, I confirmed my app keep running while 5 minutes without terminating under packet loss.

Although, when timeout is 1 sec, my app terminate eaven if no packet loss.

Please check your code around the timeout.

Best Regards,

**Comment by geysee** [comment]
Hi, 

The following your fix seems necessary.
https://github.com/amosavian/AMSMB2/issues/44#issuecomment-567867931

Because, when I run my app with "gracefully = false" without fix, my app terminate as follows.

![Thread18_0](https://user-images.githubusercontent.com/3407398/71339182-1d975300-2596-11ea-8e99-f126c7b75de7.png)
[callstackWhenTerminatedWithoutFixingDisconnectShare.zip](https://github.com/amosavian/AMSMB2/files/3993839/callstackWhenTerminatedWithoutFixingDisconnectShare.zip)


Please release this fix.

And please continue checking related to timeout.
https://github.com/amosavian/AMSMB2/issues/44#issuecomment-568333313

Best Regards,

**Comment by geysee** [comment]
Hi,

Unfortunately, my app also crashed when the timeout was set to 60 seconds.
https://github.com/amosavian/AMSMB2/issues/44#issuecomment-568333313

Please next your fixed code.

Best Regards,

**Comment by geysee** [comment]
Hi,

I think the cause is following:
In async_await function, the cb(CBData) variable is disposed when exiting the async_await function due to a timeout.
Although, after timeout,  in generic_handler callback, the libsmb2.lib use the cb which was already disposed.

Best Regards,

**Comment by geysee** [comment]
Hi, 

I fixed Context.swift following.
Now I'm testing.

- This code allocate memory for CBData with UnsafeMutablePointer.
- This code is not automatically freed CBData Memory when exiting function scope.
- It is nessesary to change async_await_pdu function as same.
```
    @discardableResult
    func async_await<DataType>(dataHandler: @escaping ContextHandler<DataType>, execute handler: ContextHandler<Int32>)
        throws -> (result: Int32, data: DataType)
    {
        return try withThreadSafeContext { (context) -> (Int32, DataType) in
            let cb = UnsafeMutablePointer<CBData>.allocate(capacity: 1)
            cb.initialize(to: CBData())
            var resultData: DataType?
            var dataHandlerError: Error?
            cb.pointee.dataHandler = { ptr in
                do {
                    resultData = try dataHandler(context, ptr)
                } catch {
                    dataHandlerError = error
                }
            }
            let result = try handler(context, cb)
            try POSIXError.throwIfError(result, description: error)
            try wait_for_reply(cb)
            let cbResult = cb.pointee.result
            
            try POSIXError.throwIfError(cbResult, description: error)
            if let error = dataHandlerError { throw error }
            return try (cbResult, resultData.unwrap())
        }
    }
```

- This code deallocate memory for CBData when callback function was finished.
- libsmb2.lib free CBData Memory when callback was finished, too.
- So, when Context.swift does not deallocate CBData memory for timeout , I expect that libsmb2.lib free CBData memory.
```
    private func wait_for_reply(_ cb: UnsafeMutablePointer<CBData>) throws {
        let startDate = Date()
        while !cb.pointee.isFinished {
            var pfd = pollfd()
            pfd.fd = fileDescriptor
            pfd.events = try whichEvents()
            
            if pfd.fd < 0 || (poll(&pfd, 1, 1000) < 0 && errno != EAGAIN) {
                throw POSIXError(.init(errno), description: error)
            }
            
            if pfd.revents == 0 {
                if timeout > 0, Date().timeIntervalSince(startDate) > timeout {
                    throw POSIXError(.ETIMEDOUT)
                }
                continue
            }
            
            try service(revents: Int32(pfd.revents))
        }
        
        cb.deallocate()
    }
```

- As a safty, I have set conditions so that CBData can be used safely in callbacks.
```
    static let generic_handler: smb2_command_cb = { smb2, status, command_data, cbdata in
        do {
            guard try smb2.unwrap().pointee.fd >= 0 else { return }
            let cbdata = try cbdata.unwrap().bindMemory(to: CBData.self, capacity: 1).pointee
            if status != SMB2_STATUS_SUCCESS {
                cbdata.result = status
            }
            if cbdata.isFinished == false {
                if let dataHandler = cbdata.dataHandler {
                    dataHandler(command_data)
                }
                cbdata.isFinished = true
            }
        } catch { }
    }
```

I have made other fix. So I will report after adjustments.

Best Regards,

**Comment by geysee** [comment]
My test was failed...

**Comment by geysee** [comment]
Hi, 

I added the code that Execute self.context = nil, smb2_destroy_context(context) when timeouted.

```
    private func wait_for_reply(_ cb: UnsafeMutablePointer<CBData>) throws {
        let startDate = Date()
        while !cb.pointee.isFinished {
            var pfd = pollfd()
            pfd.fd = fileDescriptor
            pfd.events = try whichEvents()
            
            if pfd.fd < 0 || (poll(&pfd, 1, 1000) < 0 && errno != EAGAIN) {
                throw POSIXError(.init(errno), description: error)
            }
            
            if pfd.revents == 0 {
                if timeout > 0, Date().timeIntervalSince(startDate) > timeout {
                    try? withThreadSafeContext { (context) in
                        self.context = nil
                        smb2_destroy_context(context)
                    }
                    throw POSIXError(.ETIMEDOUT)
                }
                continue
            }
            
            try service(revents: Int32(pfd.revents))
        }
    }
```

And, I changed timing that cb.deallocate()

```
    @discardableResult
    func async_await<DataType>(dataHandler: @escaping ContextHandler<DataType>, execute handler: ContextHandler<Int32>) //【要検討】
        throws -> (result: Int32, data: DataType)
    {
        return try withThreadSafeContext { (context) -> (Int32, DataType) in
            let cb = UnsafeMutablePointer<CBData>.allocate(capacity: 1)
            cb.initialize(to: CBData())
            var resultData: DataType?
            var dataHandlerError: Error?
            cb.pointee.dataHandler = { ptr in
                do {
                    resultData = try dataHandler(context, ptr)
                } catch {
                    dataHandlerError = error
                }
            }
            let result = try handler(context, cb)
            try POSIXError.throwIfError(result, description: error)
            try wait_for_reply(cb)
            let cbResult = cb.pointee.result
            cb.deallocate()
            
            try POSIXError.throwIfError(cbResult, description: error)
            if let error = dataHandlerError { throw error }
            return try (cbResult, resultData.unwrap())
        }
    }
```

I am testing now.
My next response will be after 2020/1/6, If I will still continue using your library.

Best Regards,

**Comment by geysee** [comment]
Hi,

My app has continued running for 9 days from 2019/12/27.
I am continuing testing.

Best Regards,

**Comment by geysee** [comment]
Hi, 

The following code was found to leak memory, so I decided not to use it.
https://github.com/amosavian/AMSMB2/issues/44#issuecomment-568890042

I created pull request which fixed this issue.
Please merge it.
https://github.com/amosavian/AMSMB2/pull/45#issue-359848059

Best Regards,

**Comment by geysee** [comment]
Hi, 

About following code,
https://github.com/amosavian/AMSMB2/blob/d122db1842e6a89767034a2584f90412f1af0cc3/AMSMB2/Context.swift#L329

Do you think it's necessary to add the following code, too?
```

if pfd.fd < 0 || (poll(&pfd, 1, 1000) < 0 && errno != EAGAIN) {
    try? withThreadSafeContext { (context) in
        self.context = nil
        smb2_destroy_context(context)
    }
    throw POSIXError(.init(errno), description: error)
}
```

Because I don't understand the following code. Please tell me.
`if pfd.fd < 0 || (poll(&pfd, 1, 1000) < 0 && errno != EAGAIN) {`

My app with the latest commit crashed 3 times. However, it has not occurred since then. And I do not know whether the cause is same.

Best Regards,

**Comment by geysee** [comment]
Hi,

> My app with the latest commit crashed 3 times. However, it has not occurred since then. And I do not know whether the cause is same.

The cause of this crash was not in AMSMB but in my application.
I'm very sorry.

**Comment by geysee** [comment]
The issue seems to be resolved.
I will close the issue.

I appreciate your cooperation, It was very helpful.
Thank you.
