### ISSUE TITLE
Depending on some server, the error message "Inconsitency in writing to SMB file handle." is thrown.

### ISSUE THREAD

**Issue by geysee** [amosavian/AMSMB2#46]
Hi,

Thank you for your software and your response.
I have new problem and fixed code.

### Problem
Depending on some server, the error message "Inconsitency in writing to SMB file handle." is thrown.

### Source code location
https://github.com/amosavian/AMSMB2/blob/d122db1842e6a89767034a2584f90412f1af0cc3/AMSMB2/AMSMB2.swift#L1005

### Cause
On some server, smb2_get_max_write_size returns 65536.
But returned written size from following code is 61440.
```
let written = try file.write(data: segment)
if written != segment.count {
    throw POSIXError(.EIO, description: "Inconsitency in writing to SMB file handle.")
}
```

### Fixed code
It seems some server issue, but Windows OS can write to this server without problem.
So I fixed it with the following code.
```
var written = try file.write(data: segment)

while written < segment.count {
    let partialWritten = try file.write(data: segment.suffix(segment.count - written))
    if partialWritten <= 0 {
        throw POSIXError(.EIO, description: "Inconsitency in writing to SMB file handle.")
    }
    written += partialWritten
}
```
This fix has been tested.

I will create pull request soon.
Please merge it.

Best Regards,

**Comment by geysee** [comment]
Hi,

I created pull request.
https://github.com/amosavian/AMSMB2/pull/47

Best Regards,

**Comment by geysee** [comment]
Hi,

Thank you for your reply about pull request.
https://github.com/amosavian/AMSMB2/pull/47#issuecomment-571556856

I checked packet.
I confirmed that smb2_write_async in libsmb2 is requesting with 61440 size.

I guess that the size has been changed to 61440 by the following function in libsmb2, but it is difficult to understand for me.

Please let me know if you notice any cause.

```
int
smb2_pwrite_async(struct smb2_context *smb2, struct smb2fh *fh,
                  uint8_t *buf, uint32_t count, uint64_t offset,
                  smb2_command_cb cb, void *cb_data)
{
        struct smb2_write_request req;
        struct rw_data *rd;
        struct smb2_pdu *pdu;
        int needed_credits = (count - 1) / 65536 + 1;

        if (count > smb2->max_write_size) {
                count = smb2->max_write_size;
        }
        if (smb2->dialect > SMB2_VERSION_0202) {
                if (needed_credits > MAX_CREDITS - 16) {
                        count =  (MAX_CREDITS - 16) * 65536;
                }
                needed_credits = (count - 1) / 65536 + 1;
                if (needed_credits > smb2->credits) {
                        count = smb2->credits * 65536;
                }
        } else {
                if (count > 65536) {
                        count = 65536;
                }
        }

        rd = calloc(1, sizeof(struct rw_data));
        if (rd == NULL) {
                smb2_set_error(smb2, "Failed to allocate rw_data");
                return -ENOMEM;
        }
                
        rd->cb = cb;
        rd->cb_data = cb_data;
        rd->fh = fh;
        rd->offset = offset;

        memset(&req, 0, sizeof(struct smb2_write_request));
        req.length = count;
        req.offset = offset;
        req.buf = buf;
        memcpy(req.file_id, fh->file_id, SMB2_FD_SIZE);
        req.channel = SMB2_CHANNEL_NONE;
        req.remaining_bytes = 0;
        req.flags = 0;

        pdu = smb2_cmd_write_async(smb2, &req, write_cb, rd);
        if (pdu == NULL) {
                smb2_set_error(smb2, "Failed to create write command");
                return -ENOMEM;
        }
        smb2_queue_pdu(smb2, pdu);

        return 0;
} 
```

Best Regards,

**Comment by amosavian** [comment]
Please check this issue https://github.com/amosavian/AMSMB2/issues/17

**Comment by geysee** [comment]
Hi,

Thank you for your reply.

I confirmed libsmb2 code, but I do not still understand why libsmb2 request to SMB server with 61440 byte. 

However, as you advised, by setting a chunk size to 61440, my app was able to write files to the SMB server correctly.

Thank you very much.

By the way, the SMB protocol version of this server is 2.2

> https://github.com/sahlberg/libsmb2/issues/43#issuecomment-392449832

I captured packet of iPad with Mac PC and following command, without jailbreak.
I'm sorry if you already know.
 - Before capture packet : `rvictl -s [UUID of iOS Device]`
 - After capture packet : `rvictl -x [UUID of iOS Device]`
https://developer.apple.com/documentation/network/recording_a_packet_trace

**Comment by amosavian** [comment]
> I confirmed libsmb2 code, but I do not still understand why libsmb2 request to SMB server with 61440 byte.

This value is changed to 65535 bytes in latest release.

**Comment by geysee** [comment]
Hi,

It may be fixed in following commit of libsmb2.
https://github.com/sahlberg/libsmb2/commit/aaad1ba426f4a257e83186e0d57e4ba90ad3b879

This was committed 22 days ago.

Does the following "libsmb2.a" in AMSMB2 contain this commit?
https://github.com/amosavian/AMSMB2/tree/master/libsmb2/lib

On the other hand, this commit is after v3.0.0 tag.
I am worried that this commit may not be stable.

**Comment by geysee** [comment]
Hi,

I tried chunk size to less than 61440.
But, error message "Inconsitency in writing to SMB file handle" was thrown as same.

So that, It seems that this issue has not resolved by this commit .
https://github.com/sahlberg/libsmb2/commit/aaad1ba426f4a257e83186e0d57e4ba90ad3b879

As you advised, by setting a chunk size to 61440, my app was able to write files to the SMB server correctly.
https://github.com/amosavian/AMSMB2/issues/46#issuecomment-571913103

I will close the issue.
Thank you very much for your advice.
