### ISSUE TITLE
Issue with Swift Package

### ISSUE THREAD

**Issue by sree-86** [amosavian/AMSMB2#48]
Hey thanks for this library.

**### Problem:**

When I try to add this library using Swift Package, I get this error:

`/Users/user/Documents/AMSMB2/Package.swift: package has unsupported layout; modulemap '/Users/user/Documents/AMSMB2/libsmb2/include/module.modulemap' should be inside the 'include' directory`

**Comment by amosavian** [comment]
This library is not compatible with SPM, otherwise I would mention that on readme. I'm awaiting for binary artifact support in SPM which will be released in next Swift version.
