### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by JacKFJ** [amosavian/AMSMB2#49]
when I test The file "AMSMB2Tests",I meet this Situation:
 "Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedFailureReason=Error code 1: }"

this is My Setting:
```
        let smb = AMSMB2(url: URL(string: "smb://192.168.169.1/share")!, credential: URLCredential(user: "admin", password: "admin", persistence: .forSession))!
        smb.listShares { result in ...
```

No more detail Info ，I can not go on with it.

**Comment by amosavian** [comment]
Can you try with new version? I think you may get a better error now.
