### ISSUE TITLE
Detect SMB Version

### ISSUE THREAD

**Issue by anonymouz4** [amosavian/AMSMB2#5]
Is there any way to detect what version a SMB Server is using/supporting as a client?

Just in general, doesn't have to do with iOS/Swift

**Comment by amosavian** [comment]
I don’t get the question. This library is client and supports connecting to SMB2 server and its dialects.

**Comment by anonymouz4** [comment]
Whether it is a SMB2 Server or not?

**Comment by amosavian** [comment]
This library strictly suppoert

This library does not provide any way to detect server support. It only will return an error if server doesn’t support SMB2/3 protocol or fails to establish a connection.

You can use a SMB1 library like `libdsm` (or its objective-c wrappers) as fallback.

**Comment by anonymouz4** [comment]
My problem is that it doesn't return an error, it only timeouts.

But I'm talking about a method to detect in general besides this library, if there is any (MacOS/Linux)

**Comment by amosavian** [comment]
Probably the server doesn’t return anything.

**Comment by anonymouz4** [comment]
Well it could also be a slow connection or slow dns Server that is resolving a hostname. So I don't want to wait 2 minutes to find out whether I need SMBv1 or SMBv2/3

**Comment by anonymouz4** [comment]
There has to be a way
How is the MacOS Finder then doing it? It always and instantly take the best Version?

**Comment by amosavian** [comment]
Of course there is. Please read [this link](https://msdn.microsoft.com/en-us/library/cc246792.aspx) to know how this can be done.  But the underlying library (libsmb2) supports no protocol other than SMB2 protocol and its dialects and there is no intention to add SMB1/CIFS support. But you can use [libdsm](https://github.com/videolabs/libdsm)  to add SMB1/CIFS support.
