### ISSUE TITLE
moveItem Error

### ISSUE THREAD

**Issue by carrieddd** [amosavian/AMSMB2#53]
How to moveItem 
 smb.moveItem(atPath: "22/2/1.PNG", toPath: "22/1.PNG") { (error) in
                    XCTAssertNil(error)
                    expectation.fulfill()
}

Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSLocalizedFailureReason=Error code 2: }

**Comment by amosavian** [comment]
As it describes, "22/2/1.PNG" does not exists.
