### ISSUE TITLE
STATUS_BAD_NETWORK_NAME

### ISSUE THREAD

**Issue by m8tec** [amosavian/AMSMB2#55]
Hello,

I want to connect to my Windows 10 Laptop but always get this error message: 
`Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc00000cc) STATUS_BAD_NETWORK_NAME. }`

Does anyone know what's the error?

**Comment by amosavian** [comment]
I think you are trying to connect to a non-existing share. I think you will find a better description if you search the status code (`STATUS_BAD_NETWORK_NAME`) in Google.

**Comment by m8tec** [comment]
No, I tried multiple shares and they all worked in other apps or on other devices

**Comment by MrWilsonXu** [comment]
I have the same problem 'Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc00000cc) STATUS_BAD_NETWORK_NAME. }', it's not a non-existing share

**Comment by MrWilsonXu** [comment]
> No, I tried multiple shares and they all worked in other apps or on other devices

how do you fix it ??? please tell me

**Comment by AmyF** [comment]
> @MrWilsonXu @m8tec I faced the same problem. But it was my miss to choose the right share.

```swift
let serverURL = URL(string: "smb://xxx.xxx.xx.xx")!
let credential = URLCredential(user: "xxx", password: "xxx", persistence: URLCredential.Persistence.forSession)
let share = "share"
...
try await client.connectShare(name: self.share)
```
The above code will give you access to "smb://xxx.xxx.xx.xx/share", where `share` refers to the `share` directory under the root directory of your smb sharing service. So you need to change `share` to a directory that exists in your root directory
