### ISSUE TITLE
Getting error : Could not find module 'AMSMB2' for target 'armv7-apple-ios'; found:arm64,arm64-apple-ios

### ISSUE THREAD

**Issue by kheravarun08** [amosavian/AMSMB2#56]
Hi,
Thanks for making a wonderful library.

In the latest Xcode 11.4 with MacOS Catalina I am getting error as follows : 
Could not find module 'AMSMB2' for target 'armv7-apple-ios'; found:arm64,arm64-apple-ios

Kindly help us to resolve the issue as soon as possible.
Also please integrate the current Library with SMB3 as macOS Catalina supports SMB3 version only

**Comment by kheravarun08** [comment]
We are using copyitem method to copy files from remote windows/Mac device to iPad OS 13 device.

**Comment by amosavian** [comment]
Hi,
SMB3 is partially supported. See [libsmb2 readme](https://github.com/sahlberg/libsmb2) for more details.
I will build with new version and it will probably fixed.

**Comment by amosavian** [comment]
Please use version 3.0.0
