### ISSUE TITLE
Duplicated path

### ISSUE THREAD

**Issue by DemianSteelstone** [amosavian/AMSMB2#57]
Hi!
There is a path duplication if you try to get attributes of folder.
For example, If you try to get the attributes of the folder located "/folder", you will get:
attributes[.pathKey] == "/folder/folder"

**Comment by MartinP7r** [comment]
The path always includes the actual item. So if you have a `folder` at a path `/folder` it will be `/folder/folder`. Equally a `file.md` at a path `/folder` will have a path property of `/folder/file.md`

**Comment by DemianSteelstone** [comment]
Full path of a folder "/root/1"
but when I try to get the attributes, I get the path value "/root/1/1"

**Comment by MartinP7r** [comment]
i stumbled onto the same problem on one of my servers!  
Just like you described, the path is `/folder/file`, however the retrieved `NSURLPathKey` says `/folder/file/file`.  
On top of that, I can't seem to be able to download the file...

Did you by any chance find a workaround for this?

**Comment by amosavian** [comment]
It is fixed by now.
Thanks.
@MartinP7r @DemianSteelstone
