### ISSUE TITLE
Failed to move item

### ISSUE THREAD

**Issue by DemianSteelstone** [amosavian/AMSMB2#58]
I can’t move the object, maybe I missed something? 
Here is my code sample:
```
[self.client connectShareWithName:"shareName" completionHandler:^(NSError * _Nullable error) {
        if (!error) {
            [self.client moveItemAtPath:"testFolder1/testItem.txt"
                                     toPath:"testFolder2/testItem.txt"
                          completionHandler:^(NSError * _Nullable error) {
                if (error) {
                    [weakSelf alertError:error];
                } else {
                    [weakSelf finish];
                }
            }];
        } else {
            [weakSelf alertError:error];
        }
    }];
```
As a result, I get an error
`Error Domain=NSPOSIXErrorDomain Code=5 "Input/output error" UserInfo={NSLocalizedFailureReason=Error code 5: }`

**Comment by DemianSteelstone** [comment]
Ok, this is looks like https://github.com/sahlberg/libsmb2/issues/52
When I replace '/' with '\\' in paths it starts to work

**Comment by amosavian** [comment]
That's weird. It supposed to be fixed. I will add sanitizer again until the new fix in libsmb2

**Comment by geofstro** [comment]
I have a similar problem with a Windows share. I can list all the items in a directory; but I can't fetch the data from any file.
