### ISSUE TITLE
append data to already existing file?

### ISSUE THREAD

**Issue by MartinP7r** [amosavian/AMSMB2#59]
Thank you for providing this library!

I've been looking through the implementation and didn't find a way to write to an already existing file. Using 

```
write<DataType>(data: DataType, toPath path: String, progress: WriteProgressHandler, completionHandler: SimpleCompletionHandler)
``` 

throws 

```
Optional(Error Domain=NSPOSIXErrorDomain Code=17 "File exists" UserInfo={NSLocalizedFailureReason=Error code 17: Open failed with (0xc0000035) STATUS_OBJECT_NAME_COLLISION.})
```
because it's trying to create a new file.

**Comment by amosavian** [comment]
I didn't expose any method to append data to existing files. Technically it should be poosible.

**Comment by MartinP7r** [comment]
Thanks for your reply. I see.  
file operations would probably a lot easier if there's a **override** and **append** option on the write method or some similar implementation.  
Otherwise, I guess the only way is checking if the file exists -> then download -> edit -> delete the original file -> upload new file ?

**Comment by amosavian** [comment]
i rechecked and found why I did not implement appending feature. libsmb2 does not implement `lseek()` with `SEEK_END` parameter in order to get to end of file. There are some workarounds. I'll try them.

**Comment by MartinP7r** [comment]
Did you find a way around the libsmb2 limitation?

**Comment by MartinP7r** [comment]
I implemented a workaround for myself, getting the current filesize via `attributesOfItem(atPath:)` and using that as an offset for `pwrite(data:,offset:)`.  
If you have the time, maybe you can let me know if you think that's OK as a workaround.

**Comment by senojsitruc** [comment]
> I implemented a workaround for myself, getting the current filesize via `attributesOfItem(atPath:)` and using that as an offset for `pwrite(data:,offset:)`.
> If you have the time, maybe you can let me know if you think that's OK as a workaround.

@MartinP7r Would you mind sharing your solution? I've tried the same thing (`attributesOfItem(atPath:)` combined with calling `pwrite()` instead of `write()`. It will make the initial write to create the file, but subsequent writes (at a non-zero offset) don't fail, but also don't seem to actually do anything. My test includes using `O_RDWR | O_CREAT | O_APPEND` when creating the `SMB2FileHandle`.

Any thoughts on what I'm doing wrong?

**Comment by amosavian** [comment]
@MartinP7r It's now possible by `append(data:toPath:offset:progress:)` method to add new data to end of file. Please not you must have the file size if you want to have no data loss.
