### ISSUE TITLE
User name with "/" not working 

### ISSUE THREAD

**Issue by prakash-wilcosource** [amosavian/AMSMB2#62]
ipaddress = "smb://123.23.35.1"
username = "user"
password = "password"
folderName = "name of shared folder"

it's working fine. when the user name only in text. 
it's not working when user name "somename\user" is like this. Error is code=36 session setup failed with STATUS_LOGON_FAILUR
username = "somename/user"

Xcode 11.3.1
Swift 5
iOS 13.2

**Comment by buskr** [comment]
Use "somename\\user"

**Comment by amosavian** [comment]
Username must not contains backslash otherwise it will be interpreted as `workgroup + "\" + actual user name`.
