### ISSUE TITLE
Error for listShares "NSPOSIXErrorDomain Code 22 Invalid argument"

### ISSUE THREAD

**Issue by emilhornlund** [amosavian/AMSMB2#7]
Hi!

I get the following error when trying the `listShares` function when I connect to my Mac. The `connectShare` works fine and so does `listDirectory`

> Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedFailureReason=Error code 22: }

My code
```
let client = AMSMB2(url: URL(string: "smb://192.168.0.4/")!, credential: URLCredential(user: "user", password: "pass", persistence: .forSession))

client?.connectShare(name: "Downloads", completionHandler: { (error) in
	print("connectShare")
	print(error)
})
            
client?.listShares(enumerateHidden: false, completionHandler: { (names, comments, error) in
	print("listShares")
	print(names)
	print(comments)
	print(error)
})
```

Console
```
connectShare
nil
listShares
[]
[]
Optional(Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedFailureReason=Error code 22: })
```

Same problem in Simulator as on Device

Thanks!

**Comment by amosavian** [comment]
What is your server?

Would you mind to set a breakpoint at `Context.swift line 274` to see if this error is thrown by my library or this is thrown by libsmb2?

**Comment by emilhornlund** [comment]
Nope the app executes as normal.

Just the basic file sharing toggle inside preferences for macOS high sierra

**Comment by emilhornlund** [comment]
Dont know if it helps but in `Context.swift` at line `306`
`let cbResult = cbPtr.bindMemory(to: CBData.self, capacity: 1).pointee.result`
returns -22

and the error is then thrown at the next line `307`
`try POSIXError.throwIfError(cbResult, description: error, default: defaultError)`

**Comment by amosavian** [comment]
Ok that means libsmb2 throws error. Please check `Context.error` which is error description

**Comment by amosavian** [comment]
Thus error is thrown by either [this line](https://github.com/sahlberg/libsmb2/blob/master/lib/dcerpc.c#L1028) or [this line](https://github.com/sahlberg/libsmb2/blob/master/lib/dcerpc.c#L1144)

Please record packets by Wireshark app if possible and then open an issue in [sahlberg/libsmb2](https://github.com/sahlberg/libsmb2)

**Comment by emilhornlund** [comment]
Thank you for your help, I will investigate further.

**Comment by amosavian** [comment]
@emilhornlund @hholtmann Unfortunately Sahlberg's fix is not ready yet, and I think it would not be ready until next weekend or more. I restored my own implementation which predates libsmb2's one. It have no issue as it uses read/write instead of ioctl.

I will switch back to libsmb2's when it becomes ready and stable.

**Comment by MartinP7r** [comment]
Seems like he has merged the fix a couple of months later: https://github.com/sahlberg/libsmb2/issues/63#issuecomment-437843912
