### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"

### ISSUE THREAD

**Issue by jessegillespie** [amosavian/AMSMB2#70]
Wondering if by any chance there is any other sample code available for this?  Was able to successfully add the package into a simple test app but every connection attempt is producing the error:

> Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"

The SMB server works fine for other utilities. The network diagnostic tool shows an active connection to the IP address on port 445, but also it shows zero bytes sent or received.

For what it's worth, below is the relevant code:

`
    class ViewController: UIViewController {
        var myclient:SMBClient = SMBClient()
        
        let hanlderBlock: (Result<AMSMB2, Error>) -> Void = {_ in
          print("Running handler block.")
         }
        
        override func viewDidLoad() {
            super.viewDidLoad()
            // Do any additional setup after loading the view.
            print("Viewcontroller loaded.")
        }
        
        @IBAction func Connect(_ sender: Any) {
            myclient.connect(handler: hanlderBlock)
        }
        
        @IBAction func testListDirectory(_ sender: Any) {
            print("Getting directory list.")
            myclient.listDirectory(path: "")
        }
    }

    class SMBClient {
        /// connect to: `smb://guest@XXX.XXX.XX.XX/share`
        
        let serverURL = URL(string: "smb://192.165.3.5")!
        let credential = URLCredential(user: "username", password: "password", persistence: URLCredential.Persistence.forSession)
        let share = "sharedDirectory"
        
        lazy private var client = AMSMB2(url: self.serverURL, credential: self.credential)!
        
        func connect(handler: @escaping (Result<AMSMB2, Error>) -> Void) {
            // AMSMB2 can handle queueing connection requests
            print("connect function initiated.")
            client.connectShare(name: self.share) { error in
                if let error = error {
                    handler(.failure(error))
                    print("Connection failed. Handling error.")
                } else {
                    handler(.success(self.client))
                }
            }
        }
        
        func listDirectory(path: String) {
            connect { result in
                switch result {
                case .success(let client):
                    client.contentsOfDirectory(atPath: path) { result in
                        switch result {
                        case .success(let files):
                            for entry in files {
                                print("name:", entry[.nameKey] as! String,
                                      ", path:", entry[.pathKey] as! String,
                                      ", type:", entry[.fileResourceTypeKey] as! URLFileResourceType,
                                      ", size:", entry[.fileSizeKey] as! Int64,
                                      ", modified:", entry[.contentModificationDateKey] as! Date,
                                      ", created:", entry[.creationDateKey] as! Date)
                            }
                            
                        case .failure(let error):
                            print(error)
                        }
                    }
                    
                case .failure(let error):
                    print("Failed to connect!")
                    print(error)
                }
            }
        }
        
        func moveItem(path: String, to toPath: String) {
            self.connect { result in
                switch result {
                case .success(let client):
                    client.moveItem(atPath: path, toPath: toPath) { error in
                        if let error = error {
                            print(error)
                        } else {
                            print("\(path) moved successfully.")
                        }
                        
                        // Disconnecting is optional, it will be called eventually
                        // when `AMSMB2` object is freed.
                        // You may call it explicitly to detect errors.
                        client.disconnectShare(completionHandler: { (error) in
                            if let error = error {
                                print(error)
                            }
                        })
                    }
                    
                case .failure(let error):
                    print(error)
                }
            }
        }
    }

`

**Comment by beks6** [comment]
What's the name of your share? Is it really sharedDirectory?
