### ISSUE TITLE
STATUS_LOGON_FAILURE

### ISSUE THREAD

**Issue by 0-mykola** [amosavian/AMSMB2#72]
Im stuck with a simple connection to my another macbook. I always get error when use checked (successfully connected with finder) before credentials. I always got this error

Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc000006d) STATUS_LOGON_FAILURE}

When I use guest I receive

Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc000006e) STATUS_ACCOUNT_RESTRICTION}

Any suggestions?
Thx.

**Comment by kasimok** [comment]
@amosavian Same for me, I think this is easy to reproduce, currently amsmb2 cannot connect to macos shared volumes. I also get this error:
`Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc000006d) STATUS_LOGON_FAILURE}
`

**Comment by kasimok** [comment]
@0-mykola I fixed it, please check my pull request: https://github.com/kasimok/AMSMB2
BTW, be sure to check this:
![Uploading Screenshot 2021-03-24 at 4.21.40 PM.png…]()

**Comment by 0-mykola** [comment]
@kasimok Yep, I now about this checkbox, I found out about this before.
I noticed that the problem with the login is also observed when connecting to Windows, I have a 3 laptops on windows, where one work connect successful, but other 2 failed with STATUS_LOGON_FAILURE.

I will check your pull request, and feedback.
Thank you.
