### ISSUE TITLE
listShares error

### ISSUE THREAD

**Issue by MartinP7r** [amosavian/AMSMB2#76]
Depending on the server, `listShares` fails with the error:

`Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedFailureReason=Error code 22: }`

I've found #7 , however if you've already recompiled your libsmb after November '18 it should probably be fixed. Is that the case? Then the problem most likely lies somewhere else.

I've dug into your good and trying the `shareEnumSwift()` method works for some of this failing servers, however, a remaining subset fails with 

`Error Domain=NSPOSIXErrorDomain Code=96 "No message available on STREAM" UserInfo={NSLocalizedFailureReason=Invalid/Empty data.}`

Some server's work fine. I have yet to find a difference in their setup. Maybe you know something?

**Comment by amosavian** [comment]
The only possible case is when server response is in invalid format.
