### ISSUE TITLE
Xcode compile for iOS target with swift package

### ISSUE THREAD

**Issue by mgriebling** [amosavian/AMSMB2#77]
Getting the following error in Xcode 12.5.1 on MacOS 11.4 for an iOS target using your package:

<img width="663" alt="Screen Shot 2021-07-23 at 8 22 09 AM" src="https://user-images.githubusercontent.com/2421348/126781195-8d3783be-091e-41bd-a9e5-fe38cb303c03.png">

**Comment by RichardBauer** [comment]
I had the same issue.  The /lib folder in /libsmb2 was empty on first run.  Resetting the cache and updating the package from the menu in Xcode > File > Swift Packages resulted in the ios, macos and tvos versions of the libsmb2 libraries appearing where expected.

**Comment by mgriebling** [comment]
Still have the same issue and the libsmb2 libraries are showing up in the lib directory.

**Comment by simonaplin** [comment]
I have the same issue and yes, the libraries are present in the lib directory. N.B. I am using an M1 Mac.

**Comment by Yoorque** [comment]
I can confirm the issue exists. lib/ contains all 3 platforms files, but SMB2 module still accessible.
This error also appears: 
Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'AMSMB2' from project 'AMSMB2')
@amosavian Any idea?

**Comment by beks6** [comment]
same issue here

M1 Mac
XCode 13.2.1

**Comment by beks6** [comment]
I think the problem here is, since AMSMB2 doesn't support SPM yet (or ever will) you need to add the project as a framework to your projects as described in the part `git submodule .....`

I did that and now I'm able to build without the error

**Comment by victorBaro** [comment]
@beks6 can you elaborate on how did you get that to work? I tried following the steps, adding the ASMSB2.xcodeproj into my workspace and adding ASMBS2.framework, however when trying to build with an M1 mac I see the following error:

`The linked and embedded framework 'AMSMB2.framework' is missing one or more architectures required by this target: arm64.`

**Comment by beks6** [comment]
have you added the framework under Targets - Frameworks, Libraries and Embedded Content as "Embed & Sign"

Otherwise have checked this
https://developer.apple.com/forums/thread/661163

I didn't run into this issue.

My environment

Xcode 13.2.1
iOS Deployment Targets 15.2

**Comment by OmranK** [comment]
Fixed this issue in #89.
