### ISSUE TITLE
iOS 15 fails with STATUS_LOGON_FAILURE

### ISSUE THREAD

**Issue by victorBaro** [amosavian/AMSMB2#78]
Hello, this library used to work perfectly with iOS14. After upgrading to iOS 15, it has started failing with the following error:

```
Error Domain=NSPOSIXErrorDomain Code=36 "Operation now in progress" 
UserInfo={NSLocalizedFailureReason=Session setup failed with (0xc000006d) STATUS_LOGON_FAILURE}
```

Any advice? Thank you

**Comment by MrWilsonXu** [comment]
how did you fix it ??

**Comment by victorBaro** [comment]
Still not working

**Comment by beks6** [comment]
Did you checked on your machine? I am able to connect with iOS 15.2.1

**Comment by beks6** [comment]
Check also #72 there seems to be already an approach to a solution
