### ISSUE TITLE
Swift privacy adaptions (It does not compile)

### ISSUE THREAD

**Issue by danielgaston** [amosavian/AMSMB2#8]
Change all 'private' coincidences by 'fileprivate' in AMSMB2.swift. It does not compile for the latest Swift version.

**Comment by amosavian** [comment]
Pardon my curiosity. Which version of swift do you have? I had no problem compiling with Swift 4.2.

**Comment by danielgaston** [comment]
my bad, you are right, it does compile. Not sure what happened. Sorry for the caused inconveniences.
