### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by Yoorque** [amosavian/AMSMB2#80]
First of all, I would like to thank you for making this library. It is really useful and user friendly 👍 
Nevertheless, distribution with the library as a submodule seem to be a little tricky. It would be great if SPM support was on it's way, since I use SPM for other libraries in my project and I'm reluctant to mix dependency managers.
Do you have an estimate when the SPM support will be available?

Thanks again. Your effort is much appreciated.

**Comment by beks6** [comment]
Leaving a comment for others

This project doesn't support SPM, you can import it with the git link into XCode through "Add Packages", but you will fail to build as described in issue #77

**Comment by OmranK** [comment]
Fixed in #89

**Comment by beks6** [comment]
I get a warning on the package 

"Source files for target SMB2 should be located under /Users/user/Library/Developer/Xcode/DerivedData/AppName-{hash}/SourcePackages/checkouts/AMSMB2/libsmb2"

and an error in AMSMB2.swift

No such module 'SMB2'

when adding the package to my project

**Comment by OmranK** [comment]
Package manager automatically pulls the latest tag which is currently a prior commit to the one with the fix. 

@amosavian can you please make a new tag/release so people can get the fixed package.

@beks6 you can fork the repo and create a tag for the latest commit and it will work in the meantime.

**Comment by amosavian** [comment]
Please use version 3.0.0
