### ISSUE TITLE
can someone know how to fix this 

### ISSUE THREAD

**Issue by naradd** [amosavian/AMSMB2#81]
Unable to install [/Users//Desktop/insta_flutter/build/ios/iphonesimulator/Runner.app]() on DC348557-FE81-4F61-9158-ACD98C993260. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain a valid CFBundleVersion.
Ensure your bundle contains a valid CFBundleVersion.
  Command: xcrun simctl install DC348557-FE81-4F61-9158-ACD98C993260 [/Users//Desktop/insta_flutter/build/ios/iphonesimulator/Runner.app]()
Error launching application on iPhone 11 Pro.

**Comment by amosavian** [comment]
Please use version 3.0.0
