### ISSUE TITLE
Upload the file keeping the original creation date

### ISSUE THREAD

**Issue by Steady7go** [amosavian/AMSMB2#82]
Tell me please. I am uploading files from phone to computer using the "uploadItem" function. Is it possible to somehow save the original modification date of the created file? Or might it be possible to change the date after the copy is complete? Thanks in advance.

**Comment by amosavian** [comment]
Hi @Steady7go,
by using version 3.2.0 you can use `setAttributes(attributes:ofItemAtPath:)` to change `creationDate` of file.
