### ISSUE TITLE
Uploading a folder

### ISSUE THREAD

**Issue by w0rsti** [amosavian/AMSMB2#87]
Hey there,
first of all, thanks for the lib!

I am currently trying to implement an iOS File Provider Extension using your library but I have the following problem:
When I import a File into my File Provider Extension the system will notify me with a file url containing a copy of the file.
When I am importing a GarageBand file though, I get an Folder Path, since GarageBand files seem to be a "folder" instead of a file itself.

So the URL's path I am getting is 
file:///private/var/mobile/Library/Application%20Support/FileProvider/B72C3FE7-794D-4569-A53E-BD32C8650EB2/wharf/wharf/propagate/340338/

If i pass this to the lib, i get the error "Is a directory. Code: 22"

Any Ideas how I can upload a folder as a file?

**Comment by amosavian** [comment]
Hi @w0rsti,

Unfortunately there is no method to recursively upload a folder.

You may first create the directories using`createDirectory(atPath:completionHandler:)` method,
then iterating files inside folder and uploading them one by one.
