### ISSUE TITLE
import AMSMB2 to xCode

### ISSUE THREAD

**Issue by lotze1234** [amosavian/AMSMB2#88]
Sorry,

It try to include everything to xcode to my project. 
It is not possible for me.

Can somebody explain, how to include the framework ect. to my xcode project?
Is the first time that i have problems.

What i did.... 

Add a project ... move in terminal to the folder. Edit my pod file . And do a pod install. Everything green. Install success.

What else i have to do?

Thanks a lot. I feel like newbie ;-)

**Comment by amosavian** [comment]
Please use SwiftPM instead.
