### ISSUE TITLE
macOS arm64 architecture missing

### ISSUE THREAD

**Issue by OmranK** [amosavian/AMSMB2#90]
The libsmb2-macos.a fat binary is missing arm64 support so cannot build on M1 Macs.

**Comment by BTRLabs** [comment]
Any chance you could just mirror the XCFramework solution used by the following project for building libsmb2 for any xcode target?

https://github.com/sbooth/AudioXCFrameworks

**Comment by pkluz** [comment]
+1

**Comment by amosavian** [comment]
Please use version 3.0.0
