### ISSUE TITLE
Need support for M1 iphone simulator "arm64-apple-ios-simulator"

### ISSUE THREAD

**Issue by xiaotianhu** [amosavian/AMSMB2#94]
It's ok to use this lib on Intel macbook in xcode,but on m1 macbook,it must use rosetta to build for the simulator, or xcode may report "Could not find module 'AMSMB2' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator".

Please add support for the arm64-apple-ios-simulator, the libsmb2 may already supported it.

**Comment by amosavian** [comment]
Please use version 3.0.0
