### ISSUE TITLE
Build error: unsafe build flags 

### ISSUE THREAD

**Issue by hajinhoe** [amosavian/AMSMB2#97]
Hello, I am trying to using AMSMB2(3.0.0) to my app. (Xcode 15.0.1, iOS APP)
and I was encountered build error like this:

**The package product 'AMSMB2' cannot be used as a dependency of this target because it uses unsafe build flags.**

Could anyone give me tip for this error...??

**Comment by karelrooted** [comment]
encounter the same problem ,  build success after changing amsmb2 package from branch to commit

**Comment by amosavian** [comment]
Please update to version [3.2.1](https://github.com/amosavian/AMSMB2/releases/tag/3.2.1)
@hajinhoe @karelrooted

**Comment by hajinhoe** [comment]
Thanks quick response!

But, I was able to build by removing

```
                .unsafeFlags([
                    "-Wno-everything",
                ]),
```

also from package.swift file manually.

**Comment by karelrooted** [comment]
> Please update to version [3.2.1](https://github.com/amosavian/AMSMB2/releases/tag/3.2.1) @hajinhoe @karelrooted

there is still a unsafeflags in the 3.2.1  file (-Wno-everything)

**Comment by amosavian** [comment]
Please check again with 3.2.2 @hajinhoe

**Comment by karelrooted** [comment]
> Please check again with 3.2.2 @hajinhoe

with 3.2.2 , still the same error, there is no error on your end ?  (already try clean build folder , did no work )

the only way works on my end is with unsafeflag and use commit instead of branch (need to clean build folder after change to commit)

**Comment by hajinhoe** [comment]
@amosavian Thanks very much! I was succeed build with 3.2.2.

@karelrooted Did you tried removing files on DerivedData? I have tried building after removing DerivedData and claen build folder.

**Comment by karelrooted** [comment]
> @amosavian Thanks very much! I was succeed build with 3.2.2.
> 
> @karelrooted Did you tried removing files on DerivedData? I have tried building after removing DerivedData and claen build folder and success.

it worked,  did you know what is causing this ?  I have tried reset package cache and clean build folder before , also did not work ,   reset package cache did not clear all things related to the package?
